OMP: add to changelog and detect libvmem

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -813,6 +813,8 @@ IBV_LIBS
 IBV_CFLAGS
 UNW_LIBS
 UNW_CFLAGS
+VMEM_LIBS
+VMEM_CFLAGS
 MPC_HAVE_AM_FALSE
 MPC_HAVE_AM_TRUE
 FFI_LIBS
@@ -1016,6 +1018,9 @@ enable_am
 with_libffi
 with_libffi_include
 with_libffi_libs
+with_libvmem
+with_libvmem_include
+with_libvmem_libs
 with_libunwind
 with_libunwind_include
 with_libunwind_libs
@@ -1095,6 +1100,8 @@ ALLOC_CFLAGS
 ALLOC_LIBS
 FFI_CFLAGS
 FFI_LIBS
+VMEM_CFLAGS
+VMEM_LIBS
 UNW_CFLAGS
 UNW_LIBS
 IBV_CFLAGS
@@ -1794,6 +1801,9 @@ Optional Packages:
   --with-libffi           Provide prefix for libffi
   --with-libffi-inc       Provide include path for libffi
   --with-libffi-libs      Provide library path for libffi
+  --with-libvmem          Provide prefix for libvmem
+  --with-libvmem-inc      Provide include path for libvmem
+  --with-libvmem-libs     Provide library path for libvmem
   --with-libunwind        Provide prefix for libunwind
   --with-libunwind-inc    Provide include path for libunwind
   --with-libunwind-libs   Provide library path for libunwind
@@ -1864,6 +1874,8 @@ Some influential environment variables:
   ALLOC_LIBS  linker flags for ALLOC, overriding pkg-config
   FFI_CFLAGS  C compiler flags for FFI, overriding pkg-config
   FFI_LIBS    linker flags for FFI, overriding pkg-config
+  VMEM_CFLAGS C compiler flags for VMEM, overriding pkg-config
+  VMEM_LIBS   linker flags for VMEM, overriding pkg-config
   UNW_CFLAGS  C compiler flags for UNW, overriding pkg-config
   UNW_LIBS    linker flags for UNW, overriding pkg-config
   IBV_CFLAGS  C compiler flags for IBV, overriding pkg-config
@@ -24685,6 +24697,197 @@ fi
 
 
 #
+# Detect libvmem
+#
+mpc_libvmem="no"
+
+# First use the pkgconfig naming scheme
+
+
+
+# Check whether --with-libvmem was given.
+if test "${with_libvmem+set}" = set; then :
+  withval=$with_libvmem; whole_prefix=$withval
+else
+  whole_prefix="/usr/"
+fi
+
+
+                inc_prefix=""
+
+# Check whether --with-libvmem-include was given.
+if test "${with_libvmem_include+set}" = set; then :
+  withval=$with_libvmem_include; inc_prefix=$withval
+fi
+
+                lib_prefix=""
+
+# Check whether --with-libvmem-libs was given.
+if test "${with_libvmem_libs+set}" = set; then :
+  withval=$with_libvmem_libs; lib_prefix=$withval
+else
+  lib_prefix=""
+fi
+
+
+                check_or_infer_prefix_result="no"
+                header_name=libvmem.h
+                libname=libvmem
+                alt_libname=
+                function_name=vmem_create
+                var_prefix=VMEM
+                version=""
+
+                if test -z "$lib_prefix"
+                then
+                        lib_prefix="$whole_prefix/lib"
+                else
+                        if test -d "${lib_prefix}/pkgconfig"; then
+                            export PKG_CONFIG_PATH="${lib_prefix}/lib/pkgconfig":${PKG_CONFIG_PATH}
+                        fi
+                fi
+
+                if test ! -z "$whole_prefix"
+                then
+                        if test -d "${whole_prefix}/lib/pkgconfig"; then
+                            export PKG_CONFIG_PATH="${whole_prefix}/lib/pkgconfig":${PKG_CONFIG_PATH}
+                        fi
+                fi
+
+                if test -z "$inc_prefix"
+                then
+                        inc_prefix="$whole_prefix/include/"
+                fi
+
+
+
+
+                #echo "PREF : $whole_prefix LIB: $lib_prefix INC: $inc_prefix"
+
+                # First try with PKG config
+                { $as_echo "$as_me:${as_lineno-$LINENO}: Locating $libname$version with pkg-config" >&5
+$as_echo "$as_me: Locating $libname$version with pkg-config" >&6;}
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for VMEM" >&5
+$as_echo_n "checking for VMEM... " >&6; }
+
+if test -n "$VMEM_CFLAGS"; then
+    pkg_cv_VMEM_CFLAGS="$VMEM_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"\$libname \$version\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "$libname $version") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_VMEM_CFLAGS=`$PKG_CONFIG --cflags "$libname $version" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$VMEM_LIBS"; then
+    pkg_cv_VMEM_LIBS="$VMEM_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"\$libname \$version\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "$libname $version") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_VMEM_LIBS=`$PKG_CONFIG --libs "$libname $version" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        VMEM_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "$libname $version" 2>&1`
+        else
+	        VMEM_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "$libname $version" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$VMEM_PKG_ERRORS" >&5
+
+	pkg_found=0
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	pkg_found=0
+else
+	VMEM_CFLAGS=$pkg_cv_VMEM_CFLAGS
+	VMEM_LIBS=$pkg_cv_VMEM_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	pkg_found=1
+fi
+
+                if test "x$pkg_found" = "x1"
+                then
+                        # Ensure PKG config dependencies are also
+                        # injected using RPATH
+                        VMEM_LIBS=$(promote_to_rpath ${VMEM_LIBS})
+
+                        #Insert flags
+                        CPPFLAGS="${VMEM_CFLAGS} $CPPFLAGS"
+                        LDFLAGS="${VMEM_LIBS} $LDFLAGS"
+
+
+
+
+                        #AC_MSG_NOTICE([$libname found using pkg-config])
+                        #AC_CHECK_LIB($libname,$function_name,[], [AC_MSG_ERROR([Could not locate '$function_name' in '$libname'])])
+                        check_or_infer_prefix_result="yes"
+                else
+                        __check_or_infer_prefix_include "$header_name" "$inc_prefix" "$var_prefix"
+
+                        if test -n "${alt_libname}"; then
+                                libname="${alt_libname}"
+                        fi
+
+                        __check_or_infer_prefix_lib "$libname" "$function_name" "$lib_prefix" "$var_prefix"
+
+                        if test "x$check_or_infer_prefix_include" = "xyes" -a "x$check_or_infer_prefix_lib" = "xyes"
+                        then
+                                check_or_infer_prefix_result="yes"
+                        else
+                                check_or_infer_prefix_result="no"
+                        fi
+                fi
+
+                mpc_dep_found=$check_or_infer_prefix_result
+
+
+if test "x$mpc_dep_found" = "xyes"; then
+
+$as_echo "#define MPC_HAVE_LIBVMEM 1" >>confdefs.h
+
+        mpc_libvmem="yes"
+fi
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking Building libvmem support" >&5
+$as_echo_n "checking Building libvmem support... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $mpc_libvmem" >&5
+$as_echo "$mpc_libvmem" >&6; }
+
+#
 # Detect libunwind
 #
 mpc_libunwind="no"
@@ -24863,7 +25066,6 @@ fi
                 mpc_dep_found=$check_or_infer_prefix_result
 
 
-#AC_MSG_CHECKING([support for libunwind library])
 if test "x$mpc_dep_found" = "xyes"; then
 
 $as_echo "#define MPC_HAVE_LIBUNWIND 1" >>confdefs.h
@@ -31584,6 +31786,7 @@ MPC_CONFIG_RESULT="\
 # Launcher............. $MPC_LAUNCHER\n\
 # Allocator............ $MPC_ALLOCATOR\n\
 # libunwind............ $mpc_libunwind\n\
+# libvmem.............. $mpc_libvmem\n\
 # libffi............... $HAVE_LIB_FFI\n\
 # DMTPC c/r............ $MPC_HAVE_DMTCP\n\
 #\n\
