COLORS : fix shell colors

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1003,6 +1003,9 @@ with_openpa_libs
 with_mpcalloc
 with_mpcalloc_include
 with_mpcalloc_libs
+with_libunwind
+with_libunwind_include
+with_libunwind_libs
 with_unwind
 with_unwind_include
 with_unwind_libs
@@ -1769,6 +1772,9 @@ Optional Packages:
   --with-mpcalloc         Provide prefix for mpcalloc
   --with-mpcalloc-inc     Provide include path for mpcalloc
   --with-mpcalloc-libs    Provide library path for mpcalloc
+  --with-libunwind        Provide prefix for libunwind
+  --with-libunwind-inc    Provide include path for libunwind
+  --with-libunwind-libs   Provide library path for libunwind
   --with-unwind           Provide prefix for unwind
   --with-unwind-inc       Provide include path for unwind
   --with-unwind-libs      Provide library path for unwind
@@ -23043,6 +23049,8 @@ main ()
     if (*(data + i) != *(data3 + i))
       return 14;
   close (fd);
+  free (data);
+  free (data3);
   return 0;
 }
 _ACEOF
@@ -24462,6 +24470,163 @@ fi
 $as_echo_n "checking support for libunwind library... " >&6; }
 mpc_libunwind="no"
 
+# First use the pkgconfig naming scheme
+
+
+
+# Check whether --with-libunwind was given.
+if test "${with_libunwind+set}" = set; then :
+  withval=$with_libunwind; whole_prefix=$withval
+else
+  whole_prefix="/usr/"
+fi
+
+
+                inc_prefix=""
+
+# Check whether --with-libunwind-include was given.
+if test "${with_libunwind_include+set}" = set; then :
+  withval=$with_libunwind_include; inc_prefix=$withval
+fi
+
+                lib_prefix=""
+
+# Check whether --with-libunwind-libs was given.
+if test "${with_libunwind_libs+set}" = set; then :
+  withval=$with_libunwind_libs; lib_prefix=$withval
+else
+  lib_prefix=""
+fi
+
+
+                check_or_infer_prefix_result="no"
+                header_name=libunwind.h
+                libname=libunwind
+                function_name=unw_init_local
+                var_prefix=UNW
+                version=""
+
+                if test -z "$lib_prefix"
+                then
+                        lib_prefix=$whole_prefix
+                fi
+
+                if test -z "$inc_prefix"
+                then
+                        inc_prefix=$whole_prefix
+                fi
+
+
+
+
+                #echo "PREF : $whole_prefix LIB: $lib_prefix INC: $inc_prefix"
+
+                # First try with PKG config
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for UNW" >&5
+$as_echo_n "checking for UNW... " >&6; }
+
+if test -n "$UNW_CFLAGS"; then
+    pkg_cv_UNW_CFLAGS="$UNW_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"\$libname \$version\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "$libname $version") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_UNW_CFLAGS=`$PKG_CONFIG --cflags "$libname $version" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$UNW_LIBS"; then
+    pkg_cv_UNW_LIBS="$UNW_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"\$libname \$version\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "$libname $version") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_UNW_LIBS=`$PKG_CONFIG --libs "$libname $version" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        UNW_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "$libname $version" 2>&1`
+        else
+	        UNW_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "$libname $version" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$UNW_PKG_ERRORS" >&5
+
+	pkg_found=0
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	pkg_found=0
+else
+	UNW_CFLAGS=$pkg_cv_UNW_CFLAGS
+	UNW_LIBS=$pkg_cv_UNW_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	pkg_found=1
+fi
+
+                if test "x$pkg_found" = "x1"
+                then
+                        # Ensure PKG config dependencies are also
+                        # injected using RPATH
+                        UNW_LIBS=$(promote_to_rpath ${UNW_LIBS})
+
+                        #Insert flags
+                        CPPFLAGS="${UNW_CFLAGS} $CPPFLAGS"
+                        LDFLAGS="${UNW_LIBS} $LDFLAGS"
+
+
+
+
+                        #AC_MSG_NOTICE([$libname found using pkg-config])
+                        #AC_CHECK_LIB($libname,$function_name,[], [AC_MSG_ERROR([Could not locate '$function_name' in '$libname'])])
+                        check_or_infer_prefix_result="yes"
+                else
+                        __check_or_infer_prefix_include "$header_name" "$inc_prefix" "$var_prefix"
+                        __check_or_infer_prefix_lib "$libname" "$function_name" "$lib_prefix" "$var_prefix"
+
+                        if test "x$check_or_infer_prefix_include" = "xyes" -a "x$check_or_infer_prefix_lib" = "xyes"
+                        then
+                                check_or_infer_prefix_result="yes"
+                        else
+                                check_or_infer_prefix_result="no"
+                        fi
+                fi
+
+                mpc_dep_found=$check_or_infer_prefix_result
+
+
+if test "x$mpc_dep_found" = "xno"; then
+        # Try to find the library
 
 
 
@@ -24615,6 +24780,7 @@ fi
 
                 mpc_dep_found=$check_or_infer_prefix_result
 
+fi
 
 #AC_MSG_CHECKING([support for libunwind library])
 if test "x$mpc_dep_found" = "xyes"; then
@@ -30221,14 +30387,17 @@ fi
 #### Shell color
 # Check whether --enable-shell-colors was given.
 if test "${enable_shell_colors+set}" = set; then :
-  enableval=$enable_shell_colors;
-$as_echo "#define MPC_ENABLE_SHELL_COLORS 1" >>confdefs.h
-
+  enableval=$enable_shell_colors; mpc_shell_color=$enableval
 else
-  : #Disabled shell-colors
+  mpc_shell_color="yes"
 fi
 
 
+if test "x${mpc_shell_color}" = "xyes"; then
+
+$as_echo "#define MPC_ENABLE_SHELL_COLORS 1" >>confdefs.h
+
+fi
 
 #### CMA support
 # Check whether --enable-cma was given.
