MPC_Accelerators: Refactor accelerator integration in build system (Cuda,OpenACC,OpenCL options)

diff --git a/installmpc b/installmpc
--- a/installmpc
+++ b/installmpc
@@ -215,8 +215,14 @@ do
 			extractAndAddPackageOption 'HWLOC_BUILD_PARAMETERS' 'hwloc' "$arg"
 			;;
 		################### CUDA ###################
-		--with-cuda)
-			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --with-cuda"
+		--with-cuda=*)
+			extractParamValue 'CUDA_PREFIX' 'with-cuda' "$arg"
+			;;
+		--with-openacc=*)
+			extractParamValue 'OPENACC_PREFIX' 'with-openacc' "$arg"
+			;;
+		--with-opencl=*)
+			extractParamValue 'OPENCL_PREFIX' 'with-opencl' "$arg"
 			;;
 		################### HWLOC ###################
 		--with-tbb=*)
@@ -503,7 +509,28 @@ fillMPCBuildParameters()
 	else
 		MPCFRAMEWORK_BUILD_PARAMETERS="'--with-hydra=${HYDRA_PREFIX}' ${MPCFRAMEWORK_BUILD_PARAMETERS}"
 	fi
+
+	if test "${CUDA_PREFIX}" = "internal"; then
+		echo "CUDA libraries are not embedded inside MPC ! Abort..."
+		exit 1
+	elif test -n "${CUDA_PREFIX}"; then
+		MPCFRAMEWORK_BUILD_PARAMETERS="--with-cuda=${CUDA_PREFIX} ${MPCFRAMEWORK_BUILD_PARAMETERS}"
+	fi
 	
+	if test "${OPENACC_PREFIX}" = "internal"; then
+		echo "OpenAcc implementation is not internally handled by MPC yet !"
+		exit 1
+	elif test -n "${OPENACC_PREFIX}"; then
+		MPCFRAMEWORK_BUILD_PARAMETERS="--with-openacc=${OPENACC_PREFIX} ${MPCFRAMEWORK_BUILD_PARAMETERS}"
+	fi
+	
+	if test "${OPENCL_PREFIX}" = "internal"; then
+		echo "OpenCL libraries are not embedded with MPC yet !"
+		exit 1
+	elif test -n "${OPENCL_PREFIX}"; then
+		MPCFRAMEWORK_BUILD_PARAMETERS="--with-opencl=${OPENCL_PREFIX} ${MPCFRAMEWORK_BUILD_PARAMETERS}"
+	fi
+
 	MPCFRAMEWORK_BUILD_PARAMETERS="'--with-libsctk_arch=\$\(PREFIX\)/' ${WRAPPER_CROSS_COMPIL} --arch=${MPC_TARGET} --compilers=\"${COMPILER_LIST}\" ${MPCFRAMEWORK_BUILD_PARAMETERS}"
 }
 
diff --git a/mpcframework/MPC_Tools/mpc_configure_extern_deps b/mpcframework/MPC_Tools/mpc_configure_extern_deps
--- a/mpcframework/MPC_Tools/mpc_configure_extern_deps
+++ b/mpcframework/MPC_Tools/mpc_configure_extern_deps
@@ -25,6 +25,8 @@
 EXTERN_NON_TESTED_LIB=""
 HWLOCK_IS_SETUP="no"
 CUDA_IS_SETUP="no"
+OPENACC_IS_SETUP="no"
+OPENCL_IS_SETUP="no"
 OPENPA_IS_SETUP="no"
 HYDRA_IS_SETUP="no"
 SLURM_IS_SETUP="no"
@@ -294,21 +296,33 @@ sctk_internal_setup_lib_cuda()
 SCTK_CHECK_LIB_CUDA()
 {
 	#mark test section
-	begin_section cuda
-
+	begin_section Cuda support
 	#setup if needed
 	sctk_internal_setup_lib_cuda
-
 	#check header
 	SCTK_CHECK_HEADER "cuda.h"
-    SCTK_CHECK_OPTION "-DMPC_Accelerators"
-    SCTK_CHECK_LDOPTION "-lcudart"
-    SCTK_CHECK_LDOPTION "-lcuda"
-
-	#end of section
+	SCTK_CHECK_LDOPTION "-lcudart"
+	SCTK_CHECK_LDOPTION "-lcuda"
 	end_section
 }
 
+SCTK_CHECK_OPENACC()
+{
+	begin_section OpenACC directives
+	echo "OpenACC Directives are not implemented in MPC yet ! Sorry for the inconvenience"
+	echo "Abort"
+	exit 1
+	end_section
+}
+
+SCTK_CHECK_LIB_OPENCL()
+{
+	begin_section OpenCL Support
+	echo "OpenCL Support is not implemented in MPC yet ! Sorry for the inconvenience"
+	echo "Abort"
+	exit 1
+	end_section
+}
 
 
 # Setup vars to use lib openpa
