MPC_Tools: Add error message in all srun variant if compiled with hydra MPC_Tools: Rename sallochydra -> salloc_hydra MPC_Tools: Add -l=help --launcher=help in addition of --launcher_list

diff --git a/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun b/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun
--- a/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun
+++ b/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun
@@ -24,6 +24,6 @@
 if [ "$SCTK_JOB_MANAGER" = "SLURM" ]; then
 	LAUNCH_COMMAND="srun $LAUNCH_OPTIONS -n $PROCESS_NB -N $NODE_NB -c $CPU_NB $BINARY $USER_ARGS $SCTK_ARGS"
 else
-	echo  "ERROR mpc is compiled without Hydra support" 1>&2
+	echo  "ERROR mpc is compiled without slurm support" 1>&2
 	exit 1
 fi
diff --git a/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun_mpcdb b/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun_mpcdb
--- a/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun_mpcdb
+++ b/mpc/MPC_Tools/mpcrun_opt/mpcrun_srun_mpcdb
@@ -19,6 +19,11 @@
 # Authors:                                                             # 
 #   - PERACHE Marc marc.perache@cea.fr                                 # 
 #                                                                      # 
-######################################################################## 
-LAUNCH_COMMAND="${MPC_BIN_DIR}/mpcdb_client srun $LAUNCH_OPTIONS -n $PROCESS_NB -N $NODE_NB -c $CPU_NB ${MPC_BIN_DIR}/mpcdb_server $BINARY $USER_ARGS $SCTK_ARGS"
+########################################################################
 
+if [ "$SCTK_JOB_MANAGER" = "SLURM" ]; then
+	LAUNCH_COMMAND="${MPC_BIN_DIR}/mpcdb_client srun $LAUNCH_OPTIONS -n $PROCESS_NB -N $NODE_NB -c $CPU_NB ${MPC_BIN_DIR}/mpcdb_server $BINARY $USER_ARGS $SCTK_ARGS"
+else
+	echo  "ERROR mpc is compiled without slurm support" 1>&2
+	exit 1
+fi
