MPC_BUILD: Add build compiler during MPC install (building fortran module)

diff --git a/mpcframework/MPC_Tools/mpc_configure_compiler b/mpcframework/MPC_Tools/mpc_configure_compiler
--- a/mpcframework/MPC_Tools/mpc_configure_compiler
+++ b/mpcframework/MPC_Tools/mpc_configure_compiler
@@ -97,7 +97,7 @@ EOF
 # Generate the main MPC compiler driver
 #
 # $1: target script (e.g., mpc_cc) 
-# $2: target language (c, c++ or fortran)
+# $2: target language (c, cxx or fortran)
 #
 printf_compiler(){
 
@@ -112,6 +112,12 @@ if test -z \${MPC_RPREFIX}; then
 	echo "################################################################"
 	exit 1
 fi
+
+die()
+{
+	printf "Error: \$@\n" 1>&2
+	exit 2
+}
 
 #used to override option w/ compiler specific when option has been provided
 # \$1: var name
@@ -238,10 +244,15 @@ fi
 # More variable definitions (Library path, show and different shades of args)
 cat << EOF >> $1
 MPC_MANAGER=\$MPC_RPREFIX/\$MPC_SUBPREFIX/bin/mpc_compiler_manager
+HOME_FILEPATH=\$MPC_RPREFIX
 CC="\`\$MPC_MANAGER get $2 1\`"
 #LIB_PATH="-Wl,-rpath,\${MPC_RPREFIX}/\${MPC_TARGET_SUBPREFIX}/\${MPC_TARGET_SUBPREFIX}/lib ${LIB_PATH}"
 if test "\$MPC_MAKEFILE" != "" ; then 
 LIB_PATH=""
+fi
+config_temp=\`\$MPC_MANAGER config-path\`
+if test -r \$config_temp; then
+	HOME_FILEPATH=\$config_temp
 fi
 
 # This variable is updated to 'echo' when '-show' is active
@@ -470,6 +481,7 @@ then
         else
 		print_if_stdout "Warning: \${CC} not known: Adding it\n"
 		\${MPC_RPREFIX}/\${MPC_SUBPREFIX}/bin/mpc_compiler_manager add $2 "\${CC}" > /dev/null
+		test "x\$?" != "x0" && die "Unable to add \$CC (because of errors above). Stop."
 		is_defined="\`\$MPC_MANAGER get_detail $2 \${CC}\`"
         fi
 fi
@@ -477,12 +489,13 @@ fi
 CC_FAMILY="\`echo \${is_defined} | cut -d":" -f1\`"
 CC_PRIV="\`echo \${is_defined} | cut -d":" -f2\`"
 CC="\`echo \${is_defined} | cut -d":" -f3\`"
+CC_HASH="\`echo \${is_defined} | cut -d":" -f4\`"
 
 #if CC does not support privatization and user provides privatization option
-if test ! -z "\${PRIV_FLAG}" -a "\${CC_PRIV}" = "N";
+if test -n "\${PRIV_FLAG}" -a -z "\${CC_PRIV}";
 then
 if test "$SCTK_MPC_PROCESS_MODE" != "1" ; then 
-	print_if_stdout "Warning: '\${CC} does not support privatization. Disabling it.'\n"
+	print_if_stdout "Warning: '\${CC}' does not support privatization. Disabling it.\n"
 	print_if_stdout "Warning: Do not consider using this compiler in thread-based mode.\n"
 fi
 	PRIV_FLAG=""
@@ -554,23 +567,19 @@ fi
 #to override binutils during the compilation
 export PATH=\${MPC_RPREFIX}/\${MPC_HOST_SUBPREFIX}/\${MPC_TARGET_SUBPREFIX}/bin/:\${PATH}
 
-#first definition of compiler & linking flags
-CFLAGS="\`\${MPC_RPREFIX}/\${MPC_HOST_SUBPREFIX}/\${MPC_TARGET_SUBPREFIX}/bin/mpc_cflags $language\`"
-LDFLAGS="\`\${MPC_RPREFIX}/\${MPC_HOST_SUBPREFIX}/\${MPC_TARGET_SUBPREFIX}/bin/mpc_ldflags $language\`"
-LDFLAGS="\$EXTRA_ADDON_FLAGS \$LDFLAGS"
-
 #Used to avoid header global variable privatization when libraries are not privatized
 #mpcmp.h and mpcmicrothread.h have been recopied from GCC patch
 MPC_UNPRIVATIZED_FILES="\${MPC_UNPRIVATIZED_FILES}:mpcmp.h:mpcmicrothread.h:"
-
 MPC_UNPRIVATIZED_VARS="\${MPC_UNPRIVATIZED_VARS}:\`preprocess_main\`"
 
+custompath=""
 EOF
 
 
 if test "$2" = "fortran" ; then 
 
 cat <<EOF >> $1
+custompath="\$HOME_FILEPATH/fmod/\$CC_HASH/"
 MPC_UNPRIVATIZED_VARS="\${MPC_UNPRIVATIZED_VARS}:mpi_status_ignore:mpi_statuses_ignore:mpi_in_place"
 EOF
 
@@ -580,6 +589,12 @@ cat <<EOF >> $1
 
 export MPC_UNPRIVATIZED_FILES
 export MPC_UNPRIVATIZED_VARS
+
+#first definition of compiler & linking flags
+CFLAGS="\`\${MPC_RPREFIX}/\${MPC_HOST_SUBPREFIX}/\${MPC_TARGET_SUBPREFIX}/bin/mpc_cflags $language \$custompath\`"
+LDFLAGS="\`\${MPC_RPREFIX}/\${MPC_HOST_SUBPREFIX}/\${MPC_TARGET_SUBPREFIX}/bin/mpc_ldflags $language \$custompath\`"
+LDFLAGS="\$EXTRA_ADDON_FLAGS \$LDFLAGS"
+
 
 EOF
 # Regular flags and compiler (C, C++ or fortran)
@@ -963,7 +978,7 @@ printf_compiler bin/mpc_cc c
 # Generate C++ compiler
 #
 sctk_echo "Preparing C++ Compiler: mpc_cxx"
-printf_compiler bin/mpc_cxx c++
+printf_compiler bin/mpc_cxx cxx
 
 #
 # Generate Fortran compiler
@@ -999,7 +1014,7 @@ printf_mpi_compiler bin/mpif08 bin/mpc_f77
 
 if test "$SCTK_CUDA" = "1"; then
 	sctk_echo "Preparing NVIDIA Compiler: mpc_nvcc"
-	printf_compiler bin/mpc_nvcc c++ "nvcc --compiler-bindir "
+	printf_compiler bin/mpc_nvcc cxx "nvcc --compiler-bindir "
 fi
 
 ########################################
diff --git a/mpcframework/MPC_Tools/mpc_configure_compiler_manager b/mpcframework/MPC_Tools/mpc_configure_compiler_manager
--- a/mpcframework/MPC_Tools/mpc_configure_compiler_manager
+++ b/mpcframework/MPC_Tools/mpc_configure_compiler_manager
@@ -25,7 +25,7 @@
 cat <<EOF > bin/mpc_compiler_manager
 #!/bin/sh
 
-list_languages="c c++ fortran"
+list_languages="c cxx fortran"
 CHECKSUM_TOOL=sha1sum
 
 if test -z \${MPC_RPREFIX}; then
@@ -34,7 +34,10 @@ if test -z \${MPC_RPREFIX}; then
 	echo "# You should source the mpcvars.sh file in root of MPC prefix  #" 1>&2
 	echo "################################################################" 1>&2
 	#attempt to guess MPC prefix = current script looks like PREFIX/host/target/bin/manager
-	MPC_RPREFIX="\`dirname \$0\`/../../../"
+	MPC_prefix=\`dirname \$0\`/../
+	MPC_RPREFIX="\$MPC_prefix/../../"
+else
+	MPC_prefix=\$MPC_RPREFIX/\$MPC_SUBPREFIX/
 fi
 
 die()
@@ -46,7 +49,7 @@ die()
 
 clean_main_files()
 {
-	rm mpc_main.c mpc_main.c++ mpc_main.fortran mpc_main.o > /dev/null 2>&1
+	rm mpc_main.c mpc_main.cxx mpc_main.fortran mpc_main.o > /dev/null 2>&1
 }
 
 build_main_files()
@@ -58,7 +61,7 @@ return 0;
 }
 EOFINT
 
-cat <<EOFINT > mpc_main.c++
+cat <<EOFINT > mpc_main.cxx
 int i;
 int main(int argc, char** argv){
 return 0;
@@ -93,7 +96,7 @@ help()
 {
 	printf "Usage: mpc_compiler_manager OPERATION LANGUAGE PATH FAMILY\n"
 	printf "\n"
-	printf "LANGUAGE belongs to {c,c++,fortran} (default: c)\n"
+	printf "LANGUAGE belongs to {c,cxx,fortran} (default: c)\n"
 	printf "PATH is the compiler path (default '1')\n"
 	printf "FAMILY is the compiler type: INTEL, GNU... (default: GNU)\n"
 	printf "OPERATION is one of the following:\n"
@@ -115,6 +118,43 @@ help()
 	exit 0
 }
 
+#######################################
+#for the following functions:
+#\$1 = compiler path
+#\$2 = privatization support
+#\$3 = unique compiler hash
+
+post_add_c()
+{
+	#nothing to do for now
+	dummy=1
+}
+
+post_add_cxx()
+{
+	#nothing to do for now
+	dummy=1
+}
+
+post_add_fortran()
+{
+	#rebuild Fortran modules and store them in HOME/.mpcompil/HASH/fmod
+	test ! -f \$COMPILER_FILEPATH/fortran_gen/fortran_build.sh && die "Unable to generate Fortran module for \$1\n"
+	mkdir -p \$COMPILER_FILEPATH/fmod/\$3
+	printf "Compiling Fortran modules for the new compiler: \$1\n"
+
+
+	#this is absolutely awful... 
+	FLAGS="\$2 -I\$MPC_prefix/include/mpcframework $SCTK_CFLAGS -L\$MPC_prefix/lib $SCTK_LDFLAGS -B\$MPC_prefix/bin"
+	CC="\`lookup_compiler c 1 | cut -f3 -d":"\` \$FLAGS -lmpc_framework"
+	FC="\$1 \$FLAGS"
+
+	MPC_MAKE_FORTRAN_INTERFACE=1 MPC_DISABLE_CONFIG=1 MPC_DISABLE_BANNER=1 sh \$COMPILER_FILEPATH/fortran_gen/fortran_build.sh "\$CC" "\$FC" "\$COMPILER_FILEPATH/fortran_gen/mpc_mpi.h" "\$COMPILER_FILEPATH/fmod/\$3/"
+	test "x\$?" != "x0" && die "Error(s) during Fortran module building for \$1"
+}
+
+
+
 add_compiler()
 {	
 	test "x\$2" = "x1" && die "Can't add a compiler if you don't provide a path."
@@ -124,7 +164,7 @@ add_compiler()
 	# -r: extended regexes
 	# -e: run script
 	# -n: does not create output (only matching w/ /p)
-	exists="\`get_compilers_in "\$1" | sed -n -re "\\,^\$3:(Y|N):\${2}:.*$,p"\`"
+	exists="\`get_compilers_in "\$1" | sed -n -e "\\,^\$3:.*:\${2}:.*$,p"\`"
 
 	if test -n "\$exists"; then 
 		old_hash="\`echo "\$exists" | cut -f4 -d":"\`"
@@ -133,15 +173,27 @@ add_compiler()
 
 	#inserting the compiler
 	build_main_files
-	PRIV_FLAG="-fmpc-privatize"
+
+	case \$3 in
+		GNU)
+			PRIV_FLAG="-fmpc-privatize"
+			;;
+		INTEL)
+			PRIV_FLAG="-mSYMTAB_mpc_privatize"
+			;;
+		PGI)
+			PRIV_FLAG=""
+			;;
+		*)
+			PRIV_FLAG=""
+	esac
+
 	\${2} \${PRIV_FLAG} -c mpc_main.\${1} > /dev/null 2>&1
-	if [ \$? -eq 0 ];
-	then
-		pattern="Y"
-	else
-		pattern="N"
-	fi
-	echo "\${3}:\${pattern}:\${2}:\${hash}" >> "\${COMPILER_FILEPATH}/.\${1}_compilers.cfg"
+	test "x\$?" != "x0" && PRIV_FLAG=""
+
+	post_add_\${1} "\$2" "\$PRIV_FLAG" "\$hash"
+
+	echo "\${3}:\${PRIV_FLAG}:\${2}:\${hash}" >> "\${COMPILER_FILEPATH}/.\${1}_compilers.cfg"
 }
 
 remove_compiler()
@@ -151,7 +203,7 @@ remove_compiler()
 	# -r: extended regexes
 	# -e: exec script
 	# "\,xxx,d": grep lines matching 'xxx' and remove them (using comma separator)
-	sed -i -re "\\,^\$3:(Y|N):\$2:.*$,d" \$COMPILER_FILEPATH/.\$1_compilers.cfg
+	sed -i -e "\\,^\$3:.*:\$2:.*$,d" \$COMPILER_FILEPATH/.\$1_compilers.cfg
 }
 
 set_default_compiler()
@@ -159,7 +211,7 @@ set_default_compiler()
 	# -r: extended regexes
 	# -e: run script
 	# -n: does output (only matching w/ /p)
-	exists="\`get_compilers_in "\$1" | sed -n -re "\\,^\$3:(Y|N):\${2}:.*$,p"\`"
+	exists="\`get_compilers_in "\$1" | sed -n -e "\\,^\$3:.*:\${2}:.*$,p"\`"
 	
 	#add it if not already done (add_compiler() does some extra stuff).
 	if test -z "\$exists"; then
@@ -180,7 +232,7 @@ stat_compilers()
 	do
 		lang_file=\${COMPILER_FILEPATH}/.\${language}_compilers.cfg
 		nb_compilers="\`cat \${lang_file} | wc -l\`"
-		nb_priv="\`cat \${lang_file} | cut -d":" -f2 | egrep "^Y$" | wc -l\`"
+		nb_priv="\`cat \${lang_file} | cut -d":" -f2 | wc -l\`"
 
 		echo "MPC \${language} compiler supports \${GRE}\${nb_compilers}\${DEF} compilers, \${RED}\${nb_priv}\${DEF} of them are able to privatize."
 	done
@@ -198,7 +250,7 @@ list_compilers()
 		if test -x \$compiler;
 		then
 			printf " * \${GRE}FOUND \${DEF}/"
-			if test "x\$priv" = "xY";
+			if test -n "\$priv";
 			then
 				printf "\${GRE} PRIV. SUPPORT OK \${DEF}"
 			else
@@ -249,7 +301,7 @@ lookup_compiler()
 		return
 	fi
 
-	echo "\`get_compilers_in "\$1" | sed -n -re "\\,^.*:(Y|N):\${2}:.*$,p"\`"
+	echo "\`get_compilers_in "\$1" | sed -n -e "\\,^.*:.*:\${2}:.*$,p"\`"
 }
 
 get_first_compiler()
@@ -330,6 +382,10 @@ case "\$1" in
 		;;
 	check|c)
 		check_compilers
+		;;
+	config-path)
+		echo "\$COMPILER_FILEPATH"
+		exit 0
 		;;
 	*)
 		die "Unknown rule: \"\$1\""
