Update GOMP symbol version

diff --git a/mpcframework/MPC_Tools/mpc_configure_makefile.orig b/mpcframework/MPC_Tools/mpc_configure_makefile.orig
--- a/mpcframework/MPC_Tools/mpc_configure_makefile.orig
+++ b/mpcframework/MPC_Tools/mpc_configure_makefile.orig
@@ -367,7 +367,7 @@ FORTAN_MPIH="${MPC_SOURCE_DIR}/MPC_MPI/include/mpc_mpi.h"
 FORTRAN_INSTALL="${PWD}/INSTALL/include/mpcframework/"
 #Call the script
 printf "\t@echo \"Generate FORTRAN MPI/OpenMP includes and modules\"">> Makefile; echo "" >> Makefile
-printf "\t@MPC_MAKE_FORTRAN_INTERFACE=1 MPC_DISABLE_CONFIG=1 MPC_DISABLE_BANNER=\"1\" LD_LIBRARY_PATH=\$(DESTDIR)/\$(OPENPA_PREFIX_INSTALL)/lib:\$(DESTDIR)/\$(HWLOC_PREFIX_INSTALL)/lib:\$(LD_LIBRARY_PATH) sh ${MPC_SOURCE_DIR}MPC_Tools/fortran_gen/fortran_gen.sh \"${FORTRAN_PYTHON}\" \"${FORTRAN_CC}\" \"${FORTRAN_FC}\" \"${FORTAN_MPIH}\" \"${FORTRAN_INSTALL}\" > fortrangen_script.log ">> Makefile; echo "" >> Makefile
+printf "\t@MPC_MAKE_FORTRAN_INTERFACE=1 MPC_DISABLE_CONFIG=1 MPC_DISABLE_BANNER=\"1\" LD_LIBRARY_PATH=\$(DESTDIR)/\$(OPENPA_PREFIX_INSTALL)/lib:\$(DESTDIR)/\$(HWLOC_PREFIX_INSTALL)/lib:\$(LD_LIBRARY_PATH) sh ${MPC_SOURCE_DIR}MPC_Tools/fortran_gen/fortran_gen.sh \"${FORTRAN_PYTHON}\" \"${FORTRAN_CC}\" \"${FORTRAN_FC}\" \"${FORTAN_MPIH}\" \"${FORTRAN_INSTALL}\" ">> Makefile; echo "" >> Makefile
 fi
 
 printf "\t@chmod -R 644 INSTALL/lib/*">> Makefile; echo "">> Makefile
@@ -384,9 +384,13 @@ printf "\t@cp -r INSTALL/lib/* \${DESTDIR}${SCTK_LIB_DIR}">> Makefile; echo "">>
 printf "\t@cp -r INSTALL/include/mpcframework/* \${DESTDIR}${SCTK_INCLUDE_DIR}">> Makefile; echo "">> Makefile
 printf "\t@cp -r INSTALL/man/* \${DESTDIR}${SCTK_MAN_DIR}">> Makefile; echo "">> Makefile
 printf "\t@echo \"Build dynamic libraries\"">> Makefile; echo "">> Makefile
-printf "\t@\$(CC)  \$(COBJ_LIST) ${EXTERN_NON_TESTED_LIB} -fPIC -shared -o \${DESTDIR}${SCTK_LIB_DIR}/libmpc_framework.so  $SCTK_LDFLAGS -Wl,--version-script=\$(MPC_SOURCE_DIR)/MPC_OpenMP/version_gomp.txt || echo \"Unable to build C shared library\"">> Makefile; echo "">> Makefile
+printf "\t@\$(CC)  \$(COBJ_LIST) ${EXTERN_NON_TESTED_LIB} -fPIC -shared -o \${DESTDIR}${SCTK_LIB_DIR}/libmpc_framework.so  $SCTK_LDFLAGS -Wl,--version-script=\$(MPC_SOURCE_DIR)/MPC_OpenMP/gomp/version_gomp.txt || echo \"Unable to build C shared library\"">> Makefile; echo "">> Makefile
 if test "$SCTK_FORTRAN" = "1"; then
-printf "\t@\$(CC) \$(FOBJ_LIST) ${EXTERN_NON_TESTED_LIB} -fPIC -shared -o \${DESTDIR}${SCTK_LIB_DIR}/libmpc_frameworkf.so $SCTK_LDFLAGS -Wl,--version-script=\$(MPC_SOURCE_DIR)/MPC_OpenMP/version_gomp.txt || echo \"Unable to build Fortran shared library\"">> Makefile; echo "">> Makefile
+<<<<<<< HEAD
+printf "\t@\$(F77) \$(FOBJ_LIST) ${EXTERN_NON_TESTED_LIB} -fPIC -shared -o \${DESTDIR}${SCTK_LIB_DIR}/libmpc_frameworkf.so $SCTK_LDFLAGS -Wl,--version-script=\$(MPC_SOURCE_DIR)/MPC_OpenMP/gomp/version_gomp.txt || echo \"Unable to build Fortran shared library\"">> Makefile; echo "">> Makefile
+=======
+printf "\t@\$(CC) \$(FOBJ_LIST) ${EXTERN_NON_TESTED_LIB} -fPIC -shared -o \${DESTDIR}${SCTK_LIB_DIR}/libmpc_frameworkf.so $SCTK_LDFLAGS|| echo \"Unable to build Fortran shared library\"">> Makefile; echo "">> Makefile
+>>>>>>> abi_gomp_intel
 fi
 printf "\t@cp -r INSTALL/bin/* \${DESTDIR}${SCTK_BIN_DIR}">> Makefile; echo "">> Makefile
 printf "\t@cp -r INSTALL/share/mpc/* \${DESTDIR}${SCTK_SHARE_DIR}">> Makefile; echo "">> Makefile
