COMPILERS: Force HOME update when MPC install is updated too in the same path

diff --git a/mpcframework/MPC_Tools/mpc_configure_compiler_manager b/mpcframework/MPC_Tools/mpc_configure_compiler_manager
--- a/mpcframework/MPC_Tools/mpc_configure_compiler_manager
+++ b/mpcframework/MPC_Tools/mpc_configure_compiler_manager
@@ -28,6 +28,7 @@ cat <<EOF > bin/mpc_compiler_manager
 #trailing spaces are needed for matching w/ 'egrep'
 list_languages=" c cxx fortran "
 CHECKSUM_TOOL=sha1sum
+CREATION_TIMESTAMP="`date -u +"%s"`"
 
 if test -z \${MPC_RPREFIX}; then
 	echo "################################################################" 1>&2
@@ -43,9 +44,15 @@ fi
 
 die()
 {
-	printf "\${RED}Error: \$@\n" 1>&2
+	printf "\${RED}Error: \$@\n\${DEF}" 1>&2
 	printf "\${RED}Error: Please see --help command.\${DEF}\n" 1>&2
 	exit 1
+}
+
+warn()
+{
+	printf "\${YEL}Warning: \$@\n\${DEF}" 1>&2
+
 }
 
 clean_main_files()
@@ -91,6 +98,42 @@ format_path()
 is_valid_language()
 {
 	\echo "\$list_languages" | egrep -q " \$1 " || die "Language \${1} not known !"
+}
+
+create_home()
+{
+	test ! -d "\${user_prefix}" || die "Error occured when creating the HOME link"
+	mkdir -p \${user_prefix}
+	echo "\$MPC_RPREFIX" | sed -e "s#//*#/#g" > \${user_prefix}/mpc_install_path
+	echo "\$CREATION_TIMESTAMP" > \${user_prefix}/.creation_timestamp
+	cp \${MPC_RPREFIX}/.*_compilers.cfg \${user_prefix}/
+	cp -r \${MPC_RPREFIX}/fortran_gen \${user_prefix}/
+	for mylang in \$list_languages
+	do
+		#copy any existing directory for each language
+		for line in \`cat \${user_prefix}/.\${mylang}_compilers.cfg | cut -f4 -d":"\`;
+		do
+			test -n "\$line" -a -d "\$MPC_RPREFIX/\$line/" && cp -r \${MPC_RPREFIX}/\$line  \$user_prefix/
+		done
+	done
+}
+
+is_valid_home()
+{
+	test -d "\$COMPILER_FILEPATH" || die "Sanity check failed !"
+	test -f "\$COMPILER_FILEPATH/mpc_install_path" || die "Sanity check failed !"
+
+	timestamp_f="\${COMPILER_FILEPATH}/.creation_timestamp"
+	#check existence for compatibility
+	if test ! -f "\$timestamp_f" -o "\$CREATION_TIMESTAMP" != "\`cat \$timestamp_f 2> /dev/null\`"; then
+
+		warn "MPC has been installed again in the same path after the HOME creation."
+		backup="\${COMPILER_FILEPATH}-backup"
+		test -d "\${backup}" && die "A backup cannot be erased. Please remove \${backup} directory"
+		warn "The HOME will be copied to \$backup and a new link will be generated"
+		mv \${COMPILER_FILEPATH} \$backup
+		create_home
+	fi
 }
 
 help()
@@ -355,6 +398,7 @@ if test -n "\$MANAGER_COLOR"; then
 RED="\`printf "\033[1;31m"\`"
 GRE="\`printf "\033[1;32m"\`"
 BLU="\`printf "\033[1;36m"\`"
+YEL="\`printf "\033[1;33m"\`"
 DEF="\`printf "\033[0;0m"\`"
 fi
 
@@ -385,25 +429,7 @@ done
 if test -z "\$COMPILER_FILEPATH"
 then
 	COMPILER_FILEPATH=\$user_prefix
-# in any 'default' case, everything should be stored in the HOME
-# 1. When the user does not have write permission in the base installation
-# 2. When the home diretory for this installation already exist (later manager usage)
-	#if the HOME installation does not exist, create it
-	if test ! -e \$user_prefix;
-	then
-		mkdir -p \$user_prefix
-		echo "\$MPC_RPREFIX" | sed -e "s#//*#/#g" > \$user_prefix/mpc_install_path
-		cp \${MPC_RPREFIX}/.*_compilers.cfg \$user_prefix/
-		cp -r \${MPC_RPREFIX}/fortran_gen \$user_prefix/
-		for lang in \$list_languages
-		do
-			#copy any existing directory for each language
-			for line in \`cat \${COMPILER_FILEPATH}/.\${lang}_compilers.cfg | cut -f4 -d":"\`;
-			do
-				test -n "\$line" -a -d "\$MPC_RPREFIX/\$line/" && cp -r \${MPC_RPREFIX}/\$line  \$user_prefix/
-			done
-		done
-	fi
+	test ! -e \$user_prefix && create_home
 fi
 
 #default values
@@ -423,6 +449,8 @@ arg="\`echo "\$ARGS" | cut -s -d" " -f4\`"
 test -n "\$4" && family="\$arg"
 
 is_valid_language "\$lang"
+# do this check only when working this the local link
+test "\$COMPILER_FILEPATH" != "\$MPC_RPREFIX" && is_valid_home
 test ! -e \$COMPILER_FILEPATH/.\${lang}_compilers.cfg && touch \$COMPILER_FILEPATH/.\${lang}_compilers.cfg 
 
 case "\$command" in
