MPC_Build: add support of --includedir=DIR in ./configure MPC_Build: add support of --bindir=DIR in ./configure MPC_Build: add support of --libdir=DIR in ./configure MPC_Build: add support of --mandir=DIR in ./configure

diff --git a/mpc/MPC_Tools/mpc_configure_makefile b/mpc/MPC_Tools/mpc_configure_makefile
--- a/mpc/MPC_Tools/mpc_configure_makefile
+++ b/mpc/MPC_Tools/mpc_configure_makefile
@@ -282,6 +282,10 @@ printf "\t@cp include/sctk_config.h INSTALL/include">> Makefile; echo "">> Makef
 printf "\t@cp include/mpc.h INSTALL/include">> Makefile; echo "">> Makefile
 printf "\t@echo \"Install in ${SCTK_PREFIX}\"">> Makefile; echo "">> Makefile
 printf "\t@mkdir -p \${DESTDIR}${SCTK_PREFIX}">> Makefile; echo "">> Makefile
+printf "\t@mkdir -p \${DESTDIR}${SCTK_BIN_DIR}">> Makefile; echo "">> Makefile
+printf "\t@mkdir -p \${DESTDIR}${SCTK_MAN_DIR}">> Makefile; echo "">> Makefile
+printf "\t@mkdir -p \${DESTDIR}${SCTK_INCLUDE_DIR}">> Makefile; echo "">> Makefile
+printf "\t@mkdir -p \${DESTDIR}${SCTK_LIB_DIR}">> Makefile; echo "">> Makefile
 printf "\t@mkdir -p INSTALL/man">> Makefile; echo "">> Makefile
 printf "\t@mkdir -p INSTALL/man/man1">> Makefile; echo "">> Makefile
 printf "\t@mkdir -p INSTALL/man/man3">> Makefile; echo "">> Makefile
@@ -322,26 +326,26 @@ printf "\t@chmod -R 755 INSTALL/bin/*">> Makefile; echo "">> Makefile
 printf "\t@chmod -R 644 INSTALL/include/*">> Makefile; echo "">> Makefile
 printf "\t@chmod 644 INSTALL/man/man1/*.1">> Makefile; echo "">> Makefile
 printf "\t@chmod 644 INSTALL/man/man3/*.3">> Makefile; echo "">> Makefile
-printf "\t@cp -r INSTALL/lib \${DESTDIR}${SCTK_PREFIX}">> Makefile; echo "">> Makefile
-printf "\t@cp -r INSTALL/include \${DESTDIR}${SCTK_PREFIX}">> Makefile; echo "">> Makefile
-printf "\t@cp -r INSTALL/man \${DESTDIR}${SCTK_PREFIX}">> Makefile; echo "">> Makefile
+printf "\t@cp -r INSTALL/lib/* \${DESTDIR}${SCTK_LIB_DIR}">> Makefile; echo "">> Makefile
+printf "\t@cp -r INSTALL/include/* \${DESTDIR}${SCTK_INCLUDE_DIR}">> Makefile; echo "">> Makefile
+printf "\t@cp -r INSTALL/man/* \${DESTDIR}${SCTK_MAN_DIR}">> Makefile; echo "">> Makefile
 printf "\t@echo \"Build dynamic libraries\"">> Makefile; echo "">> Makefile
-printf "\t@\$(CC) \$(COBJ_LIST) -fPIC -shared -o \${DESTDIR}${SCTK_PREFIX}/lib/libmpc.so $SCTK_LDFLAGS|| echo \"Unable to build C shared library\"">> Makefile; echo "">> Makefile
+printf "\t@\$(CC) \$(COBJ_LIST) -fPIC -shared -o \${DESTDIR}${SCTK_LIB_DIR}/libmpc.so $SCTK_LDFLAGS|| echo \"Unable to build C shared library\"">> Makefile; echo "">> Makefile
 if test "$SCTK_FORTRAN" = "1"; then
-printf "\t@\$(F77) \$(FOBJ_LIST) -fPIC -shared -o \${DESTDIR}${SCTK_PREFIX}/lib/libmpcf.so $SCTK_LDFLAGS|| echo \"Unable to build Fortran shared library\"">> Makefile; echo "">> Makefile
+printf "\t@\$(F77) \$(FOBJ_LIST) -fPIC -shared -o \${DESTDIR}${SCTK_LIB_DIR}/libmpcf.so $SCTK_LDFLAGS|| echo \"Unable to build Fortran shared library\"">> Makefile; echo "">> Makefile
 fi
-printf "\t@cp -r INSTALL/bin \${DESTDIR}${SCTK_PREFIX}">> Makefile; echo "">> Makefile
+printf "\t@cp -r INSTALL/bin/* \${DESTDIR}${SCTK_BIN_DIR}">> Makefile; echo "">> Makefile
 
 #
 # Rule 'uninstall'
 #
 echo "" >> Makefile
 echo "uninstall:" >> Makefile
-printf "\t@for i in  INSTALL/lib/* ; do rm -rf \${DESTDIR}${SCTK_PREFIX}/lib/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
-printf "\t@for i in  INSTALL/bin/* ; do rm -rf \${DESTDIR}${SCTK_PREFIX}/bin/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
-printf "\t@for i in  INSTALL/include/* ; do rm -rf \${DESTDIR}${SCTK_PREFIX}/include/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
-printf "\t@for i in  INSTALL/man/man1/* ; do rm -rf \${DESTDIR}${SCTK_PREFIX}/man/man1/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
-printf "\t@for i in  INSTALL/man/man3/* ; do rm -rf \${DESTDIR}${SCTK_PREFIX}/man/man3/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
+printf "\t@for i in  INSTALL/lib/* ; do rm -rf \${DESTDIR}${SCTK_LIB_DIR}/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
+printf "\t@for i in  INSTALL/bin/* ; do rm -rf \${DESTDIR}${SCTK_BIN_DIR}/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
+printf "\t@for i in  INSTALL/include/* ; do rm -rf \${DESTDIR}${SCTK_INCLUDE_DIR}/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
+printf "\t@for i in  INSTALL/man/man1/* ; do rm -rf \${DESTDIR}${SCTK_MAN_DIR}/man1/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
+printf "\t@for i in  INSTALL/man/man3/* ; do rm -rf \${DESTDIR}${SCTK_MAN_DIR}/man3/\`basename \$\$i\`; done">> Makefile; echo "">> Makefile
 
 
 TEST_RES="check_results"
