MPC_Config: First import of MPC_Config module for XML configuration sub-system

diff --git a/mpc/MPC_Tools/mpc_configure_extern_deps b/mpc/MPC_Tools/mpc_configure_extern_deps
--- a/mpc/MPC_Tools/mpc_configure_extern_deps
+++ b/mpc/MPC_Tools/mpc_configure_extern_deps
@@ -17,7 +17,7 @@
 # terms.                                                               #
 #                                                                      #
 # Authors:                                                             #
-#   - VALAT Sébastien sebastien.valat@cea.fr                           #
+#   - VALAT Sebastien sebastien.valat@cea.fr                           #
 #                                                                      #
 ########################################################################
 
@@ -28,6 +28,7 @@ OPENPA_IS_SETUP="no"
 HYDRA_IS_SETUP="no"
 SLURM_IS_SETUP="no"
 OPENIB_IS_SETUP="no"
+LIBXML_IS_SETUP="no"
 HYDRA_MODULE=${PWD}/../mpc-hydra-1.4.0_build/simple
 PMI_LIB=""
 
@@ -70,7 +71,7 @@ sctk_internal_setup_lib_slurm_default_prefix()
 # Setup vars to use lib slurm
 # Params:
 # Global variables:
-#   - SLUTM_PREFIX : path to slurm install dir.
+#   - SLURM_PREFIX : path to slurm install dir.
 # Will setup:
 #   - SCTK_CFLAGS , SCTK_ARFLAGS , SCTK_LDFLAGS , SLURM_IS_SETUP
 sctk_internal_setup_lib_slurm()
@@ -371,3 +372,55 @@ SCTK_CHECK_LIB_OPENIB()
   end_section
 }
 
+# Setup vars to use lib hwloc
+# Params :
+# Global variables :
+#   - HWLOC_USER_PREFIX : Prefix used to search hwloc, embeded to use the one from MPC package.
+#   - HWLOC_PREFIX_BUILD : Build directory where to find the internal hwloc.
+#   - HWLOC_PREFIX_INSTALL : Install directory for hwlock.
+#   - HWLOCK_IS_SETUP : To know if hwlock is already setup
+# Will setup:
+#   - SCTK_CFLAGS , SCTK_LDFLAGS , SCTK_ARFLAGS , HWLOCK_LIB
+SCTK_CHECK_LIBXML()
+{
+	#mark test section
+	begin_section libxml
+
+	#Find paths
+	if [ "$LIBXML_IS_SETUP" != "yes" ]; then
+		# For the moment, we dont use rpath
+		if [ -d "${LIBXML_PREFIX}" ]; then
+			if [ -f ${LIBXML_PREFIX}/lib64/libxml2.so ]; then
+				LIBXML_LIBDIR=${LIBXML_PREFIX}/lib64
+			elif [ -f ${LIBXML_PREFIX}/lib/libxml2.so ]; then
+				LIBXML_LIBDIR=${LIBXML_PREFIX}/lib
+			else
+				sctk_error "libxml2 found neither in ${LIBXML_PREFIX}/lib nor ${LIBXML_PREFIX}/lib64"
+				exit 1
+			fi
+			#setup vars
+			SCTK_ARFLAGS="${SCTK_ARFLAGS} ${LIBXML_LIBDIR}/libxml2.so"
+			SCTK_LDFLAGS="${SCTK_LDFLAGS} -Wl,-rpath,${LIBXML_LIBDIR} -L${LIBXML_LIBDIR}"
+			SCTK_CFLAGS="${SCTK_CFLAGS} -I${LIBXML_PREFIX}/include/libxml2"
+		elif [ ! -z "$(pkg-config --cflags libxml-2.0)" ]; then
+			LIBXML_PREFIX="$(pkg-config --libs libxml-2.0 | cut -f 1 -d ' ' | sed -e 's#/include$##' -e 's/^-I//')"
+			LIBXML_LIBDIR="$(pkg-config --libs libxml-2.0 | cut -f 1 -d ' ' | sed -e 's#/libxml2.so$##' -e 's/^-L//')"
+			SCTK_CFLAGS="${SCTK_CFLAGS} $(pkg-config --cflags libxml-2.0)"
+			SCTK_ARFLAGS="${SCTK_ARFLAGS} ${LIBXML_LIBDIR}/libxml2.so"
+			SCTK_LDFLAGS="${SCTK_LDFLAGS} -Wl,-rpath,${LIBXML_LIBDIR} -L${LIBXML_LIBDIR}"
+		else
+			error "Invalid libxml prefix : $LIBXML_PREFIX"
+			exit 1
+		fi
+	fi
+
+	#check header
+	SCTK_CHECK_HEADER "libxml/tree.h"
+	SCTK_CHECK_HEADER "libxml/parser.h"
+
+	#avoid to test -lopa if used embeded as it was not build while calling configure, so will fail
+	SCTK_CHECK_LDOPTION "-lxml2"
+
+	#end of section
+	end_section
+}
