MPC : Add pragma message detection at configure time

diff --git a/mpc/MPC_Tools/mpc_configure_common b/mpc/MPC_Tools/mpc_configure_common
--- a/mpc/MPC_Tools/mpc_configure_common
+++ b/mpc/MPC_Tools/mpc_configure_common
@@ -602,6 +602,34 @@ fi
 done
 }
 
+
+SCTK_CHECK_NOFAIL_PRAGMA_MESSAGE(){
+
+cat  << EOF  > ${SCTK_CONF_C}
+#define DO_PRAGMA(x) _Pragma (#x)
+#define TODO(x) DO_PRAGMA(message ("TODO - " #x))
+
+TODO(TEST_PRAGMA)
+
+
+int main(){
+    
+    return 0;
+}
+EOF
+	echo "File ${SCTK_CONF_C}" >> ${SCTK_CONF_LOG} 2>&1
+	cat ${SCTK_CONF_C} >> ${SCTK_CONF_LOG} 2>&1
+	echo "$SCTK_CC $SCTK_CFLAGS -Werror -Wall ${SCTK_CONF_C} -o ${SCTK_CONF_BIN} $SCTK_LDFLAGS">> ${SCTK_CONF_LOG} 2>&1
+	eval "$SCTK_CC $SCTK_CFLAGS  -Werror -Wall ${SCTK_CONF_C} -o ${SCTK_CONF_BIN} $SCTK_LDFLAGS">> ${SCTK_CONF_LOG} 2>&1
+	SCTK_SCTK_CHECK_FUNC_RES="$?"
+	rm ${SCTK_CONF_C} ${SCTK_CONF_BIN} >> ${SCTK_CONF_LOG} 2>&1
+
+}
+
+
+
+
+
 SCTK_CHECK_FUNC_NOFAIL_UNWIND(){
     for i in $1 ; do
 	SCTK_MSG_CHECKING $i
@@ -690,6 +718,7 @@ EOF
 }
 
 
+
 check_libunwind_done="0"
 check_libunwind(){
 if test "$check_libunwind_done" = "0" ; then
@@ -738,6 +767,29 @@ else
 sctk_echo "Already done"
 fi
 }
+
+
+check_pragma_message_done="0"
+check_pragma_message(){
+	if test "$check_pragma_message_done" = "0" ; then
+		begin_section "Check Pragma message support:"
+		SCTK_CHECK_NOFAIL_PRAGMA_MESSAGE
+		if test "$SCTK_SCTK_CHECK_FUNC_RES" = "0"; then
+			SCTK_CHECK_OPTION "-DSCTK_HAVE_PRAGMA_MESSAGE"
+		else
+			sctk_printf "#pragma message available: no\n"
+		fi
+		end_section
+	check_pragma_message_done="1"
+	else
+	sctk_echo "Already done"
+	fi
+}
+
+
+
+
+
 
 check_binding_done="0"
 check_binding(){
