MPC: Merge devel to new_ib branch

diff --git a/mpc/MPC_Tools/mpcrun_common b/mpc/MPC_Tools/mpcrun_common
--- a/mpc/MPC_Tools/mpcrun_common
+++ b/mpc/MPC_Tools/mpcrun_common
@@ -74,6 +74,13 @@ check_thread(){
     fi
 }
 
+mpcrun_error(){
+	echo "================ ERROR ================"
+	echo "$1"
+	echo "======================================="
+	exit 1
+}
+
 print_help(){
 cat << EOF
 Usage mpcrun [option] [--] binary [user args]
@@ -129,7 +136,7 @@ fi
 if test -f $MPC_USE_MPCRC_FILE; then
 . $MPC_USE_MPCRC_FILE
 else
-. ${BINS_HOME}_default_param
+. ${BINS_HOME}_default
 . $MPC_USE_MPCRC_FILE
 fi
 
@@ -412,20 +419,28 @@ PROCESS_NB="$TASK_NB"
 NET_TYPE="--use-mpi"
 fi
 
+# TEST Task and Process number correctness
+if test $TASK_NB -lt $PROCESS_NB;  then
+	mpcrun_error "You cannot have less tasks than processes ($TASK_NB task(s) for $PROCESS_NB processe(s))"
+fi
+
+# TEST Node and Process number correctness
+if test $PROCESS_NB -lt $NODE_NB;  then
+	mpcrun_error "You cannot have less processes than nodes ($NODE_NB nodes(s) for $PROCESS_NB processe(s))"
+fi
+
 export PROCESS_NB
 
 if test "$show" = "eval" ; then
     if test "@GNU_COMPATIBLE_WHICH@" = "1" ; then
 	which -- $BINARY > /dev/null 2>&1
 	if test "$?" != "0" ; then
-	    echo "Binary $BINARY not found"
-	    exit 1
+	    mpcrun_error "Binary $BINARY not found"
 	fi
     else
 	which $BINARY > /dev/null 2>&1
 	if test "$?" != "0" ; then
-	    echo "Binary $BINARY not found"
-	    exit 1
+	    mpcrun_error "Binary $BINARY not found"
 	fi
     fi
 fi
@@ -438,11 +453,10 @@ done
 
 MPC_STARTUP_ARGS="$SCTK_ARGS"
 if test "$MPC_MONO" != "1" ; then
-if test "$LAUNCH" != "madeleine" ; then
 export MPC_STARTUP_ARGS
 SCTK_ARGS=""
 fi
-fi
+
 
 export MPC_DISABLE
 
